- id: '1736869556746'
  alias: Lights Sunset Sunrise
  description: Automation based on sunrise/sun set
  trigger:
  - platform: sun
    event: sunset
    id: Sunset
  - platform: sun
    event: sunrise
    id: Sunrise
    offset: +00:15:00
  action:
  - service: light.turn_{{ 'on' if trigger.id == 'Sunset' else 'off' }}
    target:
      entity_id: light.porch_light
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Sunset
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.hall_light
        data:
          brightness_pct: 100
    - conditions:
      - condition: trigger
        id:
        - Sunrise
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.hall_light
    default:
    - service: logbook.log
      data:
        message: 'No Sunrise/Sunset actions (trigger: {{ trigger.id }})'
        name: Lights Sunset Sunrise Automation
        entity_id: sun.sun
- id: '1736963481981'
  alias: Fertigation
  description: ''
  triggers:
  - at: 03:30:00
    trigger: time
  - at: 07:30:00
    trigger: time
  - at: '11:30:00'
    trigger: time
  - at: '15:30:00'
    trigger: time
  actions:
  - target:
      entity_id: switch.tp_link_smart_plug_c82e_feed_pump
    action: switch.turn_on
    data: {}
  - target:
      entity_id: switch.tp_link_smart_plug_c82e_waste_pump
    action: switch.turn_on
    data: {}
  - delay:
      seconds: 20
  - target:
      entity_id: switch.tp_link_smart_plug_c82e_feed_pump
    action: switch.turn_off
    data: {}
  - delay:
      minutes: 2
  - target:
      entity_id: switch.tp_link_smart_plug_c82e_waste_pump
    action: switch.turn_off
    data: {}
  - target:
      entity_id: input_datetime.last_fertigation_time
    data:
      datetime: '{{ now().strftime(''%Y-%m-%d %H:%M:%S'') }}'
    action: input_datetime.set_datetime
  - data:
      timestamp: '{{ as_timestamp(now()) | int }}'
    action: esphome.wroommicrousb_set_last_fertigation_time
  - data:
      message: Fertigation complete!
    action: notify.mobile_app_pixel_9_pro_xl
  mode: single
- id: '1736972664016'
  alias: garage_door_always_on
  description: ''
  triggers:
  - entity_id:
    - switch.tp_link_power_strip_8bba_garage_door_opener_always_on
    to: 'off'
    trigger: state
  actions:
  - action: switch.turn_on
    data: {}
    target:
      entity_id: switch.tp_link_power_strip_8bba_garage_door_opener_always_on
  mode: single
- id: '1736972856548'
  alias: grow_lights_on
  description: ''
  triggers:
  - at: 07:00:00
    trigger: time
  actions:
  - target:
      label_id: grow_lights
    action: switch.turn_on
    data: {}
  mode: single
- id: '1736972905755'
  alias: grow_lights_off
  description: ''
  triggers:
  - at: '19:00:00'
    trigger: time
  actions:
  - target:
      label_id: grow_lights
    action: switch.turn_off
    data: {}
  mode: single
- id: '1737217638878'
  alias: pantry_light_motion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.eye_of_sauron_motion_detection
      light_target:
        device_id: f973418ec638992abe6d7ba0689bf2ed
- id: '1737669355677'
  alias: Lock after 30
  description: ''
  triggers:
  - device_id: 32836b60fdccc501e777b202da401e93
    domain: lock
    entity_id: f74b245176e9841e08f9c4c3195aa1ff
    type: unlocked
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 30
  conditions:
  - condition: state
    entity_id: binary_sensor.front_door_sensor_window_door_is_open
    state: 'off'
  actions:
  - target:
      device_id:
      - 32836b60fdccc501e777b202da401e93
    action: lock.lock
    data: {}
  - data:
      message: Front door locked
    action: notify.mobile_app_pixel_9_pro_xl
  mode: single
- id: '1738078626589'
  alias: front_door_unlock
  description: ''
  triggers:
  - entity_id:
    - lock.front_door
    from: locked
    to: unlocked
    trigger: state
  actions:
  - choose:
    - conditions:
      - condition: sun
        before: sunset
        after: sunrise
      sequence:
      - action: light.turn_on
        data:
          brightness_pct: 100
        target:
          device_id: 967c2ab1d3adc7eaae31cf22e6bad228
    - conditions: []
      sequence:
      - action: light.turn_on
        data:
          brightness_pct: 100
        target:
          device_id:
          - 967c2ab1d3adc7eaae31cf22e6bad228
          - 619b02e8104048d5e2a7472e0e4b0aee
  mode: single
- id: '1738079317260'
  alias: morning_lights
  description: ''
  triggers:
  - at: 07:00:00
    trigger: time
  actions:
  - data:
      rgb_color:
      - 255
      - 255
      - 255
      transition: 60
    action: light.turn_on
    target:
      device_id:
      - 53a38436e48c861a918ad8dfc03dce79
      - 08fe604d2c4001adaee1f2b56b998b15
  mode: single
- id: '1738256101698'
  alias: front_door_unlocked_scream
  description: ''
  triggers:
  - entity_id:
    - lock.front_door
    to: unlocked
    for:
      minutes: 5
    trigger: state
  actions:
  - action: lock.lock
    data: {}
    target:
      device_id: 32836b60fdccc501e777b202da401e93
  - data:
      message: Front Door is unlocked!
      title: Front Door unlocked
    action: notify.persistent_notification
  - data:
      title: Front Door unlocked
      message: Front Door unlocked!
    action: notify.mobile_app_pixel_9_pro_xl
  - data:
      title: Front Door unlocked
      message: Front Door unlocked
    action: notify.mobile_app_pixel_watch_3
  - action: notify.lg_webos_tv_oled65c2pua
    data:
      message: Front Door unlocked
  - target:
      entity_id: input_select.threat_level
    data:
      option: critical
    action: input_select.select_option
  mode: single
- id: '1738259251934'
  alias: Reduce threat after door lock
  description: ''
  trigger:
  - platform: state
    entity_id: lock.touchscreen_deadbolt
    from: unlocked
    to: locked
  condition:
  - condition: state
    entity_id: input_select.threat_level
    state: critical
  action:
  - service: notify.mobile_app_pixel_9_pro_xl
    data:
      message: Front Door Locked
      title: Front Door Locked
  - service: notify.mobile_app_pixel_watch_3
    data:
      message: Front Door Locked
      title: Front Door Locked
  - service: input_select.select_option
    target:
      entity_id: input_select.threat_level
    data:
      option: high
  mode: single
- id: '1739482139761'
  alias: Update Last Fertigation Time
  description: ''
  trigger:
  - platform: time
    at:
    - 03:30:00
    - 07:30:00
    - '11:30:00'
    - '15:30:00'
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.last_fertigation_time
    data:
      datetime: '{{ now().strftime(''%Y-%m-%d %H:%M:%S'') }}'
  mode: single
