# --- Frontend (Themes & Lovelace) ---
frontend:
  themes: !include_dir_merge_named themes

# --- Lovelace Configuration ---
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/mushroom-strategy.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/room-summary-card/room-summary-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom-better-sliders/mushroom.js
      type: module
    - url: /hacsfiles/hassio-trash-card/trashcard.js
      type: module


prometheus:
  namespace: homeassistant

# --- Default Integrations ---
default_config:

# --- Configuration Splits ---
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include templates.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
#recorder: !include recorder.yaml

input_text: !include input_text.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
shell_command: !include shell_command.yaml

# --- HTTP Configuration ---
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24

# --- Custom Panel ---
panel_custom:
  - name: ha_system
    sidebar_title: System Info
    sidebar_icon: mdi:information-variant
    js_url: /api/hassio/app/entrypoint.js
    url_path: "hassio/system/info"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

python_script:
# Enable Python scripts

automation blueprint:
  - source: /config/ble_discovery_automation.yaml

logger:
  default: info
  logs:
    custom_components.ab_gateway: debug

recorder:
  db_url: mysql://homeassistant:Skyw4lk3rH4z3!@core-mariadb/homeassistant




